Using device: cuda
CUDA available: True
Loading light curves...
finished getting all files
Loaded 10 light curves
/home/pdong/.conda/envs/myenv/lib/python3.11/site-packages/torch/nn/modules/transformer.py:502: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647429097/work/aten/src/ATen/NestedTensorImpl.cpp:178.)
  output = torch._nested_tensor_from_mask(
Epoch 0, Train Loss: 229032.7500, Validation Loss: 47109.7734
Epoch 100, Train Loss: 8960.2416, Validation Loss: 1711.3003
Epoch 200, Train Loss: 8196.6211, Validation Loss: 1705.3987
Epoch 300, Train Loss: 8205.2656, Validation Loss: 1701.8807
Epoch 400, Train Loss: 7832.7160, Validation Loss: 1699.6084
Epoch 500, Train Loss: 8736.4442, Validation Loss: 1696.9175
Epoch 600, Train Loss: 8323.1094, Validation Loss: 1694.0820
Epoch 700, Train Loss: 8072.4760, Validation Loss: 1689.8806
Epoch 800, Train Loss: 8430.2221, Validation Loss: 1688.2629
Epoch 900, Train Loss: 8179.0848, Validation Loss: 1683.3383
Epoch 1000, Train Loss: 8049.9916, Validation Loss: 1678.1631
Epoch 1100, Train Loss: 8486.5519, Validation Loss: 1672.5570
Epoch 1200, Train Loss: 8394.7522, Validation Loss: 1667.8953
Epoch 1300, Train Loss: 7940.7589, Validation Loss: 1665.4060
Epoch 1400, Train Loss: 8091.1110, Validation Loss: 1660.6475
Epoch 1500, Train Loss: 7586.3650, Validation Loss: 1658.1438
Epoch 1600, Train Loss: 7910.9107, Validation Loss: 1655.0389
Traceback (most recent call last):
  File "/orcd/home/002/pdong/Astro UROP/trans_model.py", line 552, in <module>
    torch.save(model.state_dict(), os.path.join(model_dir, 'transformer_vae_best.pt'))
  File "/home/pdong/.conda/envs/myenv/lib/python3.11/site-packages/torch/serialization.py", line 850, in save
    _save(
  File "/home/pdong/.conda/envs/myenv/lib/python3.11/site-packages/torch/serialization.py", line 1114, in _save
    zip_file.write_record(name, storage, num_bytes)
KeyboardInterrupt
