Using device: cuda
CUDA available: True
Loading light curves...
finished getting all files
Loaded 10 light curves
Traceback (most recent call last):
  File "/orcd/home/002/pdong/Astro UROP/trans_model.py", line 504, in <module>
    x_hat, mu, logvar, x_hat_norm = model(x, lengths)
                                    ^^^^^^^^^^^^^^^^^
  File "/home/pdong/.conda/envs/myenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pdong/.conda/envs/myenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/orcd/home/002/pdong/Astro UROP/trans_model.py", line 282, in forward
    decoded_unnorm = self.unnormalize_data(decoded)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/orcd/home/002/pdong/Astro UROP/trans_model.py", line 193, in unnormalize_data
    return x_norm * (self.max_vals - self.min_vals)[None, None, :] + self.min_vals[None, None, :]
           ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (9) must match the size of tensor b (8) at non-singleton dimension 2
